#!/usr/bin/python2

import warnings
warnings.simplefilter("ignore")

import xmpp
from xmpp.protocol import Message

from optparse import OptionParser
import ConfigParser
import sys
import os

import yaml


f = open('/etc/jabberproxy.yml')
conf = yaml.safe_load(f)
f.close()

parser = OptionParser()

parser.add_option("-u", "--username",
                  help="jabber username")
parser.add_option("-a", "--alias",
                  help="jabber alias")
parser.add_option("-p", "--pass", dest="password",
                  help="jabber password")
parser.add_option("-s", "--server",
                  help="jabber server")
parser.add_option("--port",
                  default=5222, type='int',
                  help="port to connect to")
parser.add_option("--path",
                  default="/tmp/jabberproxy",
                  help="path for fifo")

opts, args = parser.parse_args()

for k, v in opts.__dict__.iteritems():
    if v is not None:
        conf[k] = v
print(opts)
print(args)
print(conf)

uname, domain = conf["username"].split("@")
if not "alias" in conf:
    conf["alias"] = uname

if len(args) > 0:
    conf["rooms"] = args

try:
    os.mkfifo(conf["path"])
except OSError, e:
    print "Failed to create FIFO: %s" % e

# Connect to the server
c  =  xmpp.Client(domain)
c.connect((conf["server"],conf["port"]))

# Authenticate to the server
jid  =  xmpp.protocol.JID( conf["username"] )
c.auth( jid.getNode( ), conf["password"] )
for room in conf["rooms"]:
    c.send(xmpp.Presence(to='%s/%s'% (room, conf["alias"])))

while True:
    fifo = open(conf["path"], 'r')
    for msg in fifo:
        msg = msg.strip()
        if msg == "":
            continue
        msg = msg.replace('\\n', '\n')
        for room in conf["rooms"]:
            c.send(Message('%s' % room, '%s' % msg, 'groupchat'))  
    fifo.close() 
